const STORAGE_KEY='personal-finance-pwa-v1';
const defaults={balances:{cheq:60,td:1869,rbc:0},transactions:[],budgets:{Groceries:275,Transportation:330,'Eating Out':40,'Shopping / Personal':40,'Friend Repayment':75},fixed:{Rent:600,Phone:160,iCloud:12.99,'ChatGPT Plus':30,'YouTube Premium':14,'Amazon Prime + No Ads':15,'Temporary Obligation':150}};
let state=load();
const cats=[...Object.keys(defaults.fixed),...Object.keys(defaults.budgets),'Glasses','Other'];
const $=id=>document.getElementById(id); const money=n=>'$'+Number(n).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2});
function load(){try{return JSON.parse(localStorage.getItem(STORAGE_KEY))||structuredClone(defaults)}catch{return structuredClone(defaults)}}
function save(){localStorage.setItem(STORAGE_KEY,JSON.stringify(state))}
function monthKey(d){return d.slice(0,7)}
function todayStr(){const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
function apply(t,dir=1){const key=t.account==='Chequing'?'cheq':t.account==='TD Credit Card'?'td':'rbc'; let impact=0;if(t.type==='spend') impact=key==='cheq'?-t.amount:t.amount; else if(t.type==='payment') impact=-t.amount; else if(t.type==='income') impact=key==='cheq'?t.amount:-t.amount; state.balances[key]+=impact*dir}
function render(){const {cheq,td,rbc}=state.balances;$('cheqBal').textContent=money(cheq);$('tdBal').textContent=money(td);$('rbcBal').textContent=money(rbc);$('debtBal').textContent=money(td+rbc);$('tdBal').className='value '+(td>2100?'bad':td>2000?'warn':'good');$('cheqBal').className='value '+(cheq<100?'bad':cheq<200?'warn':'good'); const msgs=[];msgs.push(td>2100?'TD is over the $2,100 hard limit.':td>2000?'TD is above the $2,000 ideal target.':'TD is within the ideal target.'); msgs.push(cheq<100?'Chequing is below the $100 minimum buffer.':cheq<200?'Chequing is below the preferred $200 buffer.':'Chequing buffer is healthy.'); $('guardStatus').textContent=msgs.join(' '); renderBudgets();renderFixed();renderTx()}
function renderBudgets(){const wrap=$('budgets');wrap.innerHTML=''; const mk=monthKey(todayStr()); for(const [cat,target] of Object.entries(state.budgets)){const used=state.transactions.filter(t=>t.category===cat&&t.type==='spend'&&monthKey(t.date)===mk).reduce((s,t)=>s+t.amount,0);const remain=target-used;const pct=Math.min(100,Math.max(0,used/target*100));const div=document.createElement('div');div.className='budget';div.innerHTML=`<div class="budget-head"><span>${cat}</span><span>${money(used)} / ${money(target)}</span></div><div class="bar"><div class="fill" style="width:${pct}%"></div></div><div class="small ${remain<0?'bad':''}">${remain>=0?money(remain)+' remaining':money(Math.abs(remain))+' over target'}</div>`;wrap.appendChild(div)}}
function renderFixed(){const wrap=$('fixedCosts');wrap.innerHTML='';for(const [k,v] of Object.entries(state.fixed)){const d=document.createElement('div');d.className='fixed-item';d.innerHTML=`<div>${k}</div><div>${money(v)}</div>`;wrap.appendChild(d)}}
function renderTx(){const wrap=$('txList');wrap.innerHTML='';if(!state.transactions.length){wrap.innerHTML='<div class="sub">No transactions yet.</div>';return}state.transactions.slice().reverse().slice(0,20).forEach(t=>{const d=document.createElement('div');d.className='tx';d.innerHTML=`<div class="tx-main"><div class="tx-title">${t.desc||t.category}</div><div class="tx-meta">${t.date} · ${t.account} · ${t.category}</div></div><div class="amount">${money(t.amount)}</div>`;wrap.appendChild(d)})}
$('date').value=todayStr(); const catSel=$('category');cats.forEach(c=>{const o=document.createElement('option');o.textContent=c;catSel.appendChild(o)});
$('txForm').addEventListener('submit',e=>{e.preventDefault();const amount=parseFloat($('amount').value);if(!Number.isFinite(amount)||amount<=0){$('status').textContent='Enter a valid amount.';return}const t={id:crypto.randomUUID?crypto.randomUUID():String(Date.now()),date:$('date').value,account:$('account').value,category:$('category').value,type:$('type').value,amount,desc:$('desc').value.trim()};apply(t);state.transactions.push(t);save();$('amount').value='';$('desc').value='';$('status').textContent='Saved.';render()});
$('undoBtn').addEventListener('click',()=>{const t=state.transactions.pop();if(!t){$('status').textContent='Nothing to undo.';return}apply(t,-1);save();$('status').textContent='Last transaction undone.';render()});
$('clearBtn').addEventListener('click',()=>{if(!confirm('Clear all transactions and reset balances to starting values?'))return;state=structuredClone(defaults);save();render()});
$('exportBtn').addEventListener('click',()=>{const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='money-tracker-backup.json';a.click();URL.revokeObjectURL(a.href)});
$('importBtn').addEventListener('click',()=>$('importInput').click());$('importInput').addEventListener('change',async e=>{const f=e.target.files[0];if(!f)return;try{const imported=JSON.parse(await f.text());if(!imported.balances||!Array.isArray(imported.transactions))throw new Error();state=imported;save();render();$('status').textContent='Backup imported.'}catch{$('status').textContent='Could not import that backup.'}e.target.value=''});
let deferredPrompt;window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;$('installBtn').classList.remove('hide')});$('installBtn').addEventListener('click',async()=>{if(!deferredPrompt)return;deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null;$('installBtn').classList.add('hide')});
if('serviceWorker' in navigator) navigator.serviceWorker.register('./sw.js');render();
